id: P000533
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG03797
  title: ཐུབ་བསྟན་རྡོ་རྗེ་བྲག་དགོན་གྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ་ངོ་མཚར་བཻ་ཌཱུ་རྱའི་ཕྲེང་བ་
  author: ''
  volumes:
    8cbc3cd946e241b5b285d0421c76bc57:
      image_group_id: I00KG03832
      title: Volume 1 of thub bstan rdo rje brag dgon gyi byung ba mdo tsam brjod
        pa ngo mtshar bai DU r+ya'i phreng ba
      volume_number: 1
      total_pages: 49
      base_file: v001.txt
